modLoader="javafml"

loaderVersion="[31,)"

issueTrackerURL="http://my.issue.tracker/"

[[mods]]

modId="chrispymod"

version="0.8.0"

displayName="The Chrispy Mod"

updateJSONURL="http://myurl.me/"

displayURL="http://example.com/"

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="examplemod.png"

credits="Thanks to everyone that downloaded this mod!"

authors="cjcj55"

description='''
This mod enhances your vanilla Minecraft experience by adding
additional ores, blocks, items, foods, tools, armors, biomes, and more!

Make sure to check the mod's Curseforge page for frequent updates!!!
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.examplemod]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[31,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
